Story9/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Landing,name='Landing'),
    path('signup', views.signup,name='signup'),
    path('main', views.main,name='main'),
    path('logout',views.logout,name='logout')

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
import json
import requests
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import logout as django_logout



def Landing(request):

	if(request.method=='GET'):

		return render(request, 'main/landing.html')
	else:
		username=request.POST.get("Username")
		password=request.POST.get("Password")

		user=authenticate(username=username,password=password)
		if(user is not None):
			login(request,user)
			return redirect('main:main')

		messages.error(request,"Wrong password or username")
		return render(request,'main/landing.html')

def signup(request):

	if(request.method == 'GET'):
		
		return render(request, 'main/signup.html')
		
	else:
		username= request.POST.get("Username")
		password=request.POST.get("Password")
		try:
			user = User.objects.get(username=username)
			messages.error(request,"Username taken, try again")
			return render(request,'main/signup.html')
		except:
			user=User.objects.create_user(username=username,password=password)
			messages.success(request,"Sign up successfull")

			
			return redirect(reverse('main:signup'))

@login_required(login_url='main:Landing')
def main(request):
	if(request.method=='GET'):
		return render(request,'main/main.html')

def logout(request):
	django_logout(request)
	return redirect('main:Landing')

main/templates/main/landing.html
{% load static %}

<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style type="text/css">

body {
    background-color: white-space;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  height: 100vh;
  color: black  ;
  align-items: center;
  align-self: center;
  align-content: center ;
  text-align: center;
  

}
.center {
  margin: auto;
  width: 50%;
  padding: 10px;
}
.card {
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  width: 100%;
  margin-top: 40% ;
  padding-top: 30px;
}

.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>


</head>
<body> 

<div class= "container" style="align-items: center;">
<div class = "center"> 
<div class = "card" style="text-align: center;align-items: center;">
  <form method="POST">
    <div class="form-group">
       {% csrf_token %}
       <label>Username:</label>
       <input name="Username" id="Username" type="text" required>
   </div>
   <div class="form-group">
     <label>Password: </label>
     <input name="Password" id="Password" type="password" required>
   </div>
   <div class="form-group">
      <input type="submit" value="Log In" id="log-in" name="login" class="btn btn-warning">
  </form>
         <h4>Dont have an account yet? </h4><br>
         <a href = "{% url 'main:signup' %}">
         <input  value="Sign Up" class="btn" name="signbut" style="background-color: #38C781;">
         </a>
            {% for i in messages %}
            <h3>{{ i }}</h3>
            {% endfor %}
          
</div>
</div>
</div>

  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

</div>
</body>
</html>

main/templates/main/main.html
{% load static %}

<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style type="text/css">

body {
  background-color: black;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  height: 100vh;
  color:black;

}
</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>


</head>
<body> 

  <div class="font1">
   <div class="container pt-5 fluid" style="background-color: #e3dede;text-align: center; color: black">
      Welcome
  </div>
</div>
<div class="container pl-2">
<div class="col md-6 pt-5 pl-5" style="color: white">



  <h2> Hi, {{ user.username }}</h2>

  
            {% for i in messages %}
            <h3>{{ i }}</h3>
            {% endfor %}
            <br>
            <a href="{% url 'main:logout' %}">
            <input type="submit" value="Log out" class="btn btn-danger" name="logout">
            </a>
</div>
</div>
</div>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

</div>
</body>
</html>

main/templates/main/signup.html
{% load static %}

<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<style type="text/css">

body {
  background-color: black;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  height: 100vh;
  color:black;

}
</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>


</head>
<body> 
<div class="container pl-2">
<div class="col md-6 pt-5 pl-5" style="color: white">

  <h2> SIGN UP </h2>

  <form method="POST">
    <div class="form-group">
       {% csrf_token %}
       <label>Username:</label>
       <input name="Username" id="Username" type="text" required>
   </div>
   <div class="form-group">
     <label>Password: </label>
     <input name="Password" id="Password" type="password" required>
   </div>
   <div class="form-group">
     <a href="{% url 'main:signup' %}">
      <input type="submit" value="SIGN UP" id="log-in" class="btn btn-warning" name="signup">
      </a>
        {% for i in messages %}
        <h3>{{ i }}</h3>
        {% endfor %}


   </div>
  
  </form>
  <a href="{% url 'main:Landing' %}">
    <input type="submit" value="back to landing page" class="btn btn-warning" name="signup">
    </a>



</div>
</div>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

</div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>